### PR TITLE
RotateList.java

### PR DESCRIPTION
**Pull request by princekamariya**
This is problem no. 61 in leetcode and in this problem we have given the head of a linked list and we need to rotate the list to the right by k places.

### CODE REVIEW

**Comment by princekamariya** [comment]
Please Check My PR...

**Review by Rohithv07 — CHANGES_REQUESTED** [review]
Could you please create a new folder with your name and move the file there?
I am very happy if you do so.

**Comment by princekamariya** [comment]
Yes Sure, I will But in which folder I need to create new folder inside LinkedList folder or any other please let me know?

**Comment by Rohithv07** [comment]
You can create it inside the LinkedList folder, that will be fine.

**Comment by Rohithv07** [comment]
Thank you for contributing.

**Review by Rohithv07 — APPROVED** [review]

**Pull request merged**
